/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NbAiLabel: typeof import('@nubisco/ui/components/AiLabel')['NbAiLabel']
    NbBadge: typeof import('@nubisco/ui/components/Badge')['NbBadge']
    NbBanner: typeof import('@nubisco/ui/components/Banner')['NbBanner']
    NbBoard: typeof import('@nubisco/ui/components/Board')['NbBoard']
    NbBreadcrumbs: typeof import('@nubisco/ui/components/Breadcrumbs')['NbBreadcrumbs']
    NbButton: typeof import('@nubisco/ui/components/Button')['NbButton']
    NbCalendar: typeof import('@nubisco/ui/components/Calendar')['NbCalendar']
    NbCard: typeof import('@nubisco/ui/components/Card')['NbCard']
    NbCardGrid: typeof import('@nubisco/ui/components/CardGrid')['NbCardGrid']
    NbCheckbox: typeof import('@nubisco/ui/components/Checkbox')['NbCheckbox']
    NbCommandPalette: typeof import('@nubisco/ui/components/CommandPalette')['NbCommandPalette']
    NbDataTable: typeof import('@nubisco/ui/components/DataTable')['NbDataTable']
    NbDatePicker: typeof import('@nubisco/ui/components/DatePicker')['NbDatePicker']
    NbDefinitionList: typeof import('@nubisco/ui/components/DefinitionList')['NbDefinitionList']
    NbEmptyState: typeof import('@nubisco/ui/components/EmptyState')['NbEmptyState']
    NbField: typeof import('@nubisco/ui/components/Field')['NbField']
    NbFileUploader: typeof import('@nubisco/ui/components/FileUploader')['NbFileUploader']
    NbForm: typeof import('@nubisco/ui/components/Form')['NbForm']
    NbGanttChart: typeof import('@nubisco/ui/components/Charts/GanttChart')['NbGanttChart']
    NbIcon: typeof import('@nubisco/ui/components/Icon')['NbIcon']
    NbInlineEdit: typeof import('@nubisco/ui/components/InlineEdit')['NbInlineEdit']
    NbInlineLoading: typeof import('@nubisco/ui/components/InlineLoading')['NbInlineLoading']
    NbMenu: typeof import('@nubisco/ui/components/Menu')['NbMenu']
    NbMenuDivider: typeof import('@nubisco/ui/components/MenuDivider')['NbMenuDivider']
    NbMenuItem: typeof import('@nubisco/ui/components/MenuItem')['NbMenuItem']
    NbModal: typeof import('@nubisco/ui/components/Modal')['NbModal']
    NbNubiscoMark: typeof import('@nubisco/ui/components/NubiscoMark')['NbNubiscoMark']
    NbPanel: typeof import('@nubisco/ui/components/Panel')['NbPanel']
    NbSelect: typeof import('@nubisco/ui/components/Select')['NbSelect']
    NbShell: typeof import('@nubisco/ui/components/Shell')['NbShell']
    NbShellPanel: typeof import('@nubisco/ui/components/ShellPanel')['NbShellPanel']
    NbSidebarBrand: typeof import('@nubisco/ui/components/SidebarBrand')['NbSidebarBrand']
    NbSidebarLink: typeof import('@nubisco/ui/components/SidebarLink')['NbSidebarLink']
    NbSidebarMenu: typeof import('@nubisco/ui/components/SidebarMenu')['NbSidebarMenu']
    NbSidebarMenuGroup: typeof import('@nubisco/ui/components/SidebarMenuGroup')['NbSidebarMenuGroup']
    NbSidebarMenuItem: typeof import('@nubisco/ui/components/SidebarMenuItem')['NbSidebarMenuItem']
    NbSkeleton: typeof import('@nubisco/ui/components/Skeleton')['NbSkeleton']
    NbTabs: typeof import('@nubisco/ui/components/Tabs')['NbTabs']
    NbTextInput: typeof import('@nubisco/ui/components/TextInput')['NbTextInput']
    NbToaster: typeof import('@nubisco/ui/components/Toaster')['NbToaster']
    NbTree: typeof import('@nubisco/ui/components/Tree')['NbTree']
    NbTreeNode: typeof import('@nubisco/ui/components/TreeNode')['NbTreeNode']
    NbUserMenu: typeof import('@nubisco/ui/components/UserMenu')['NbUserMenu']
    NbWalkthrough: typeof import('@nubisco/ui/components/Walkthrough')['NbWalkthrough']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
